### ISSUE TITLE
Keys with letter "G" aren't recognized as being valid.

### ISSUE THREAD

**Issue by rustyconover** [microprediction/muid#9]
It seems that the muid.org website isn't validating keys with "g" in them, so this means there needs to be a new release pushed.

Example key:

`Pretty Name yee-dog Key: cd4abc977f240bdf4400cd624df63639 Hash: 4eed09339a747da99bb8517c2f444f5c`

Or one that is even more fun:

`Pretty Name tasty-eagle Key: 43a8546ae4c0645fc02a29b9d5d43db2 Hash: 7a574ea91ec8f6f38dda13614651b974`

**Comment by microprediction** [comment]
Yes that is right. I was waiting on your PR for the corpus change ... though I can do that if you like 


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by rustyconover** [comment]
If you merge #10 should be all set.

**Comment by microprediction** [comment]
Merged and releasing. I'll check locally and then reload the site

**Comment by microprediction** [comment]
That took a while as I bumped microconventions and microprediction and tested the crawlers. 
But...site should validate properly now
